name: Release E-Bill package

# Trigger the workflow manually
on:
  push:
    branches:
      - feature/wizard
#   workflow_dispatch:
#     inputs:
#       version:
#         description: 'Version number for the release'
#         required: true
#       release_notes:
#         description: 'Release notes for the version'
#         required: true

jobs:
  build:
    strategy:
      matrix:
        config: 
          - os: windows-latest
            pck: choco install protoc -y
            installer: 
                ver: windows-x64-installer.exe
                target: windows
                exec: builder-cli.exe
        #   - os: macos-latest
        #     pck: brew install protobuf
        #     installer: 
        #         ver: osx-installer.dmg
        #         target: osx
        #         exec: builder
    
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout BE repo
        uses: actions/checkout@v4
        with:
            path: be
    
      - name: Install BE dependencies
        run: ${{ matrix.config.pck }}

    #   - name: Build BE
    #     run: cargo build --features embedded-db --release
    #     working-directory: ./be
      
      - name: Checkout FE repo
        uses: actions/checkout@v4
        with:
            repository: BitcreditProtocol/E-Bill-frontend
            path: fe

    #   - name: Build FE
    #     run: |
    #         npm install
    #         npm run build
    #     working-directory: ./fe
      
      - name: Install InstallBuilder
        run: |
            curl -L -o installbuilder-${{ matrix.config.installer.ver }} https://releases.installbuilder.com/installbuilder/installbuilder-professional-24.11.1-${{ matrix.config.installer.ver }}
            ./installbuilder-${{ matrix.config.installer.ver }} --mode unattended
        
      - name: Build installer
        run: |
            /home/runner/installbuilder-24.11.1/bin/${{ matrix.config.installer.exec }} build spec.xml ${{ matrix.config.installer.target }}
        working-directory: ./be/.github/workflows/wizard

      - name: Upload BE artifacts
        uses: actions/upload-artifact@v4
        with:
            name: bitcredit-0.3-${{ matrix.config.installer.ver }}
            path: ./be/.github/workflows/wizard/bitcredit-0.3-${{ matrix.config.installer.ver }}
  
#   build_installer:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download artifacts
#         uses: actions/download-artifact@v4
#         with:
#             path: be

#       - name: Discover filesystem
#         run: find ~ -type d